spring.application.name=backend
# Chave secreta para assinatura dos tokens JWT.
# IMPORTANTE: Em um projeto real, esta chave deve ser muito mais complexa e
# gerenciada fora do controle de versão (ex: variáveis de ambiente).
jwt.secret=7d4a6a572a722e434f4b4e404b4e2d423f4b4e404b4e2d423f4b4e404b4e2d42